eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

server:
  port: 8005
spring:
  application:
    name: api-admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml